---
version: '3.3'

services:
  doh1:
    image: 'cslev/doh_docker:latest'
    container_name: ${R5}  #rename according to you scenario for easier identification
    privileged: true #required for ethtool and disabling offloading
    volumes:
      - './container_data/${R5}:/doh_project/archives:rw'
    
    shm_size: '4g'

    environment:
      DOH_DOCKER_NAME: ${R5}  #should be same as container_name
      DOH_DOCKER_RESOLVER: ${R5} # resolver to use
      DOH_DOCKER_START: '1' #first domain to visit in the domain list
      DOH_DOCKER_END: '5000' #last domain to visit in the domain list
      DOH_DOCKER_BATCH: '200' #how many domains to visit within a batch (don't change unless you know what you are doing)
      DOH_DOCKER_INTF: 'eth0' #change this if your container would not have eth0 as a default interface
      DOH_DOCKER_DOMAIN_LIST: 'top-1m.csv' #the relative path inside the container pointing to the list of domains to visit (in Alexa list style: id, domain <-one each line)
      DOH_DOCKER_META: 'sg' #any meta info to affix your final output files for easier identification
      DOH_DOCKER_WEBPAGE_TIMEOUT: '20' #how many seconds we wait for a website to load before throwing timeout error and skip
      DOH_DOCKER_ARCHIVE_PATH: '/doh_project/archives' #where to store the compressed output. Should be the same as defined by the 'volume'


  doh2:
    image: 'cslev/doh_docker:latest'
    container_name: ${R6}  #rename according to you scenario for easier identification
    privileged: true #required for ethtool and disabling offloading

    volumes:
      - './container_data/${R6}:/doh_project/archives:rw'

    shm_size: '4g'

    environment:
      DOH_DOCKER_NAME: ${R6}  #should be same as container_name
      DOH_DOCKER_RESOLVER: ${R6} # resolver to use
      DOH_DOCKER_START: '1' #first domain to visit in the domain list
      DOH_DOCKER_END: '5000' #last domain to visit in the domain list
      DOH_DOCKER_BATCH: '200' #how many domains to visit within a batch (don't change unless you know what you are doing)
      DOH_DOCKER_INTF: 'eth0' #change this if your container would not have eth0 as a default interface
      DOH_DOCKER_DOMAIN_LIST: 'top-1m.csv' #the relative path inside the container pointing to the list of domains to visit (in Alexa list style: id, domain <-one each line)
      DOH_DOCKER_META: 'sg' #any meta info to affix your final output files for easier identification
      DOH_DOCKER_WEBPAGE_TIMEOUT: '20' #how many seconds we wait for a website to load before throwing timeout error and skip
      DOH_DOCKER_ARCHIVE_PATH: '/doh_project/archives' #where to store the compressed output. 

  doh3:
    image: 'cslev/doh_docker:latest'
    container_name: ${R7}  #rename according to you scenario for easier identification
    privileged: true #required for ethtool and disabling offloading

    volumes:
      - './container_data/${R7}:/doh_project/archives:rw'

    shm_size: '4g'

    environment:
      DOH_DOCKER_NAME: ${R7}  #should be same as container_name
      DOH_DOCKER_RESOLVER: ${R7} # resolver to use
      DOH_DOCKER_START: '1' #first domain to visit in the domain list
      DOH_DOCKER_END: '5000' #last domain to visit in the domain list
      DOH_DOCKER_BATCH: '200' #how many domains to visit within a batch (don't change unless you know what you are doing)
      DOH_DOCKER_INTF: 'eth0' #change this if your container would not have eth0 as a default interface
      DOH_DOCKER_DOMAIN_LIST: 'top-1m.csv' #the relative path inside the container pointing to the list of domains to visit (in Alexa list style: id, domain <-one each line)
      DOH_DOCKER_META: 'sg' #any meta info to affix your final output files for easier identification
      DOH_DOCKER_WEBPAGE_TIMEOUT: '20' #how many seconds we wait for a website to load before throwing timeout error and skip
      DOH_DOCKER_ARCHIVE_PATH: '/doh_project/archives' #where to store the compressed output. 

  doh4:
    image: 'cslev/doh_docker:latest'
    container_name: ${R8}  #rename according to you scenario for easier identification
    privileged: true #required for ethtool and disabling offloading

    volumes:
      - './container_data/${R8}:/doh_project/archives:rw'
    
    shm_size: '4g'

    environment:
      DOH_DOCKER_NAME: ${R8}  #should be same as container_name
      DOH_DOCKER_RESOLVER: ${R8} # resolver to use
      DOH_DOCKER_START: '1' #first domain to visit in the domain list
      DOH_DOCKER_END: '5000' #last domain to visit in the domain list
      DOH_DOCKER_BATCH: '200' #how many domains to visit within a batch (don't change unless you know what you are doing)
      DOH_DOCKER_INTF: 'eth0' #change this if your container would not have eth0 as a default interface
      DOH_DOCKER_DOMAIN_LIST: 'top-1m.csv' #the relative path inside the container pointing to the list of domains to visit (in Alexa list style: id, domain <-one each line)
      DOH_DOCKER_META: 'sg' #any meta info to affix your final output files for easier identification
      DOH_DOCKER_WEBPAGE_TIMEOUT: '20' #how many seconds we wait for a website to load before throwing timeout error and skip
      DOH_DOCKER_ARCHIVE_PATH: '/doh_project/archives' #where to store the compressed output. 

      
